version: '3.8'

services:
  mosque-map-app:
    build: .
    ports:
      - "3000:80"
    environment:
      - NODE_ENV=production
    restart: unless-stopped
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.mosque-map.rule=Host(`your-domain.com`)"
      - "traefik.http.routers.mosque-map.tls=true"
      - "traefik.http.routers.mosque-map.tls.certresolver=letsencrypt"