name: Deploy to Production

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Login to Docker Hub
      uses: docker/login-action@v3
      with:
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}

    - name: Build and push Docker image
      uses: docker/build-push-action@v5
      with:
        context: .
        push: true
        tags: ${{ secrets.DOCKER_USERNAME }}/mosque-map-app:latest
        build-args: |
          REACT_APP_SUPABASE_URL=${{ secrets.REACT_APP_SUPABASE_URL }}
          REACT_APP_SUPABASE_ANON_KEY=${{ secrets.REACT_APP_SUPABASE_ANON_KEY }}

    - name: Deploy to server
      uses: appleboy/ssh-action@v1.0.3
      with:
        host: 5.189.174.110
        username: mustafa
        key: ${{ secrets.SERVER_SSH_KEY }}
        port: 22
        timeout: 30s
        command_timeout: 10m
        script: |
          echo "Starting deployment..."
          docker login -u ${{ secrets.DOCKER_USERNAME }} -p ${{ secrets.DOCKER_PASSWORD }}
          echo "Pulling latest image..."
          docker pull ${{ secrets.DOCKER_USERNAME }}/mosque-map-app:latest
          echo "Stopping existing container..."
          docker stop mosque-map-app || true
          docker rm mosque-map-app || true
          echo "Creating data directory..."
          mkdir -p /home/mustafa/mosque-data
          echo "Starting new container..."
          docker run -d \
            --name mosque-map-app \
            -p 3018:80 \
            -v /home/mustafa/mosque-data:/app/data \
            --restart always \
            ${{ secrets.DOCKER_USERNAME }}/mosque-map-app:latest
          echo "Cleaning up..."
          docker system prune -f
          echo "Deployment completed successfully!"