name: Build and Deploy to Server

on:
  push:
    branches: [ main ]

env:
  REGISTRY: docker.io
  IMAGE_NAME: mustafarenderrevenueai/mosque-map-app

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Set up Node.js
      uses: actions/setup-node@v4
      with:
        node-version: '18'
        cache: 'npm'

    - name: Install dependencies
      run: npm ci

    - name: Run linting
      run: npm run lint

    - name: Run type checking
      run: npm run type-check

    - name: Run tests
      run: npm test -- --coverage --watchAll=false --passWithNoTests

    - name: Build application
      run: npm run build
      env:
        REACT_APP_SUPABASE_URL: ${{ secrets.VITE_SUPABASE_URL }}
        REACT_APP_SUPABASE_ANON_KEY: ${{ secrets.VITE_SUPABASE_ANON_KEY }}

    - name: Debug Supabase Secrets
      run: |
        echo "VITE_SUPABASE_URL: ${{ secrets.VITE_SUPABASE_URL }}"
        echo "VITE_SUPABASE_ANON_KEY: ${{ secrets.VITE_SUPABASE_ANON_KEY }}"

    - name: Log in to Docker Hub
      uses: docker/login-action@v3
      with:
        registry: ${{ env.REGISTRY }}
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}

    - name: Extract metadata
      id: meta
      uses: docker/metadata-action@v5
      with:
        images: ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}
        tags: |
          type=ref,event=branch
          type=ref,event=pr
          type=sha,prefix={{branch}}-
          type=raw,value=latest,enable={{is_default_branch}}

    - name: Build and push Docker image
      uses: docker/build-push-action@v5
      with:
        context: .
        push: true
        tags: ${{ steps.meta.outputs.tags }}
        labels: ${{ steps.meta.outputs.labels }}
        build-args:
          REACT_APP_SUPABASE_URL=${{ secrets.VITE_SUPABASE_URL }}
          REACT_APP_SUPABASE_ANON_KEY=${{ secrets.VITE_SUPABASE_ANON_KEY }}

  deploy:
    needs: build
    runs-on: ubuntu-latest
    if: github.ref == 'refs/heads/main'

    steps:
    - name: Deploy to server
      uses: appleboy/ssh-action@v1.0.0
      with:
        host: ${{ secrets.SERVER_HOST }}
        username: ${{ secrets.SERVER_USER }}
        key: ${{ secrets.SERVER_SSH_KEY }}
        port: ${{ secrets.SERVER_PORT || 22 }}
        script: |
          # Login to Docker Hub
          echo ${{ secrets.DOCKER_PASSWORD }} | docker login docker.io -u ${{ secrets.DOCKER_USERNAME }} --password-stdin
          
          # Pull latest image
          docker pull mustafarenderrevenueai/mosque-map-app:latest
          
          # Stop and remove old container
          docker stop mosque-map-app || true
          docker rm mosque-map-app || true
          
          # Run new container
          docker run -d             --name mosque-map-app             --restart unless-stopped             -p 3011:80             -e REACT_APP_SUPABASE_URL=${{ secrets.VITE_SUPABASE_URL }}             -e REACT_APP_SUPABASE_ANON_KEY=${{ secrets.VITE_SUPABASE_ANON_KEY }}             mustafarenderrevenueai/mosque-map-app:latest
          
          # Clean up old images
          docker image prune -f || true