name: Deploy to Production

on:
  push:
    branches:
      - main

permissions:
  contents: read
  packages: write

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Set lowercase username
      run: echo "REPO_OWNER_LOWER=$(echo ${{ github.repository_owner }} | tr '[:upper:]' '[:lower:]')" >> $GITHUB_ENV

    - name: Login to GitHub Container Registry
      uses: docker/login-action@v3
      with:
        registry: ghcr.io
        username: ${{ github.actor }}
        password: ${{ secrets.GITHUB_TOKEN }}

    - name: Build and push to GitHub Container Registry
      uses: docker/build-push-action@v5
      with:
        context: .
        push: true
        tags: ghcr.io/${{ env.REPO_OWNER_LOWER }}/mosque-map-app:latest
        build-args: |
          REACT_APP_SUPABASE_URL=${{ secrets.REACT_APP_SUPABASE_URL }}
          REACT_APP_SUPABASE_ANON_KEY=${{ secrets.REACT_APP_SUPABASE_ANON_KEY }}

    - name: Deploy to server
      uses: appleboy/ssh-action@v1.0.3
      with:
        host: 5.189.174.110
        username: mustafa
        key: ${{ secrets.SERVER_SSH_KEY }}
        port: 22
        timeout: 30s
        command_timeout: 10m
        script: |
          echo "Starting deployment..."
          echo "Logging into GitHub Container Registry..."
          echo ${{ secrets.GITHUB_TOKEN }} | docker login ghcr.io -u ${{ github.actor }} --password-stdin
          echo "Pulling latest image from GitHub Container Registry..."
          docker pull ghcr.io/${{ env.REPO_OWNER_LOWER }}/mosque-map-app:latest
          echo "Stopping existing container..."
          docker stop mosque-map-app || true
          docker rm mosque-map-app || true
          echo "Creating data directory..."
          mkdir -p /home/mustafa/mosque-data
          echo "Starting new container..."
          docker run -d \
            --name mosque-map-app \
            -p 3011:80 \
            -v /home/mustafa/mosque-data:/app/data \
            --restart always \
            ghcr.io/${{ env.REPO_OWNER_LOWER }}/mosque-map-app:latest
          echo "Cleaning up..."
          docker system prune -f
          echo "Deployment completed successfully!"