name: Deploy to Production

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Login to Docker Hub
      uses: docker/login-action@v3
      with:
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}

    - name: Build and push Docker image
      uses: docker/build-push-action@v5
      with:
        context: .
        push: true
        tags: ${{ secrets.DOCKER_USERNAME }}/mosque-map-app:latest
        build-args: |
          REACT_APP_SUPABASE_URL=${{ secrets.REACT_APP_SUPABASE_URL }}
          REACT_APP_SUPABASE_ANON_KEY=${{ secrets.REACT_APP_SUPABASE_ANON_KEY }}

    - name: Deploy to server
      uses: appleboy/ssh-action@master
      with:
        host: ${{ secrets.SERVER_HOST }}
        username: ${{ secrets.SERVER_USERNAME }}
        key: ${{ secrets.SERVER_SSH_KEY }}
        script: |
          docker login -u ${{ secrets.DOCKER_USERNAME }} -p ${{ secrets.DOCKER_PASSWORD }}
          docker pull ${{ secrets.DOCKER_USERNAME }}/mosque-map-app:latest
          docker stop mosque-map-app || true
          docker rm mosque-map-app || true
          mkdir -p /home/${{ secrets.SERVER_USERNAME }}/mosque-data
          docker run -d \
            --name mosque-map-app \
            -p 3018:80 \
            -v /home/${{ secrets.SERVER_USERNAME }}/mosque-data:/app/data \
            --restart always \
            ${{ secrets.DOCKER_USERNAME }}/mosque-map-app:latest
          docker system prune -f